// Package edgeimpulse provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package edgeimpulse

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	ApiKeyAuthenticationScopes        = "ApiKeyAuthentication.Scopes"
	JWTAuthenticationScopes           = "JWTAuthentication.Scopes"
	JWTHttpHeaderAuthenticationScopes = "JWTHttpHeaderAuthentication.Scopes"
	OAuth2Scopes                      = "OAuth2.Scopes"
)

// Defines values for DeploymentTargetEngine.
const (
	DeploymentTargetEngineAkida                 DeploymentTargetEngine = "akida"
	DeploymentTargetEngineCevaNpn               DeploymentTargetEngine = "ceva-npn"
	DeploymentTargetEngineDrpAi                 DeploymentTargetEngine = "drp-ai"
	DeploymentTargetEngineEthosLinux            DeploymentTargetEngine = "ethos-linux"
	DeploymentTargetEngineMemryx                DeploymentTargetEngine = "memryx"
	DeploymentTargetEngineNeox                  DeploymentTargetEngine = "neox"
	DeploymentTargetEngineNordicAxon            DeploymentTargetEngine = "nordic-axon"
	DeploymentTargetEngineStAton                DeploymentTargetEngine = "st-aton"
	DeploymentTargetEngineSyntiant              DeploymentTargetEngine = "syntiant"
	DeploymentTargetEngineTensaiflow            DeploymentTargetEngine = "tensaiflow"
	DeploymentTargetEngineTensorrt              DeploymentTargetEngine = "tensorrt"
	DeploymentTargetEngineTflite                DeploymentTargetEngine = "tflite"
	DeploymentTargetEngineTfliteEon             DeploymentTargetEngine = "tflite-eon"
	DeploymentTargetEngineTfliteEonRamOptimized DeploymentTargetEngine = "tflite-eon-ram-optimized"
	DeploymentTargetEngineTidl                  DeploymentTargetEngine = "tidl"
)

// Defines values for DeviceInferenceInfoModelType.
const (
	DeviceInferenceInfoModelTypeClassification             DeviceInferenceInfoModelType = "classification"
	DeviceInferenceInfoModelTypeConstrainedObjectDetection DeviceInferenceInfoModelType = "constrainedObjectDetection"
	DeviceInferenceInfoModelTypeObjectDetection            DeviceInferenceInfoModelType = "objectDetection"
)

// Defines values for DeviceRemoteMgmtMode.
const (
	Disconnected DeviceRemoteMgmtMode = "disconnected"
	Inference    DeviceRemoteMgmtMode = "inference"
	Ingestion    DeviceRemoteMgmtMode = "ingestion"
)

// Defines values for GetJWTRequestSsoType.
const (
	Browser GetJWTRequestSsoType = "browser"
	Cli     GetJWTRequestSsoType = "cli"
)

// Defines values for KerasModelTypeEnum.
const (
	KerasModelTypeEnumAkida           KerasModelTypeEnum = "akida"
	KerasModelTypeEnumFloat32         KerasModelTypeEnum = "float32"
	KerasModelTypeEnumInt8            KerasModelTypeEnum = "int8"
	KerasModelTypeEnumRequiresRetrain KerasModelTypeEnum = "requiresRetrain"
)

// Defines values for KerasModelVariantEnum.
const (
	Akida   KerasModelVariantEnum = "akida"
	Float32 KerasModelVariantEnum = "float32"
	Int8    KerasModelVariantEnum = "int8"
)

// Defines values for ModelEngineShortEnum.
const (
	Tflite                ModelEngineShortEnum = "tflite"
	TfliteEon             ModelEngineShortEnum = "tflite-eon"
	TfliteEonRamOptimized ModelEngineShortEnum = "tflite-eon-ram-optimized"
)

// Defines values for Permission.
const (
	AdminEmailsVerificationCodeRead       Permission = "admin:emails:verification:code:read"
	AdminInfraConfigRead                  Permission = "admin:infra:config:read"
	AdminInfraConfigWrite                 Permission = "admin:infra:config:write"
	AdminInfraDisallowedEmailDomainsRead  Permission = "admin:infra:disallowedEmailDomains:read"
	AdminInfraDisallowedEmailDomainsWrite Permission = "admin:infra:disallowedEmailDomains:write"
	AdminInfraFeatureFlagsRead            Permission = "admin:infra:featureFlags:read"
	AdminInfraFeatureFlagsWrite           Permission = "admin:infra:featureFlags:write"
	AdminInfraMigrationsRead              Permission = "admin:infra:migrations:read"
	AdminInfraMigrationsWrite             Permission = "admin:infra:migrations:write"
	AdminJobsRead                         Permission = "admin:jobs:read"
	AdminMetricsRead                      Permission = "admin:metrics:read"
	AdminMetricsWrite                     Permission = "admin:metrics:write"
	AdminOauthRead                        Permission = "admin:oauth:read"
	AdminOauthWrite                       Permission = "admin:oauth:write"
	AdminOrganizationsMembersWrite        Permission = "admin:organizations:members:write"
	AdminOrganizationsRead                Permission = "admin:organizations:read"
	AdminOrganizationsWrite               Permission = "admin:organizations:write"
	AdminProjectsMembersWrite             Permission = "admin:projects:members:write"
	AdminProjectsRead                     Permission = "admin:projects:read"
	AdminProjectsWrite                    Permission = "admin:projects:write"
	AdminSsoDomainIdpsWrite               Permission = "admin:sso:domainIdps:write"
	AdminSsoRead                          Permission = "admin:sso:read"
	AdminTrashbinWrite                    Permission = "admin:trashbin:write"
	AdminTrialsRead                       Permission = "admin:trials:read"
	AdminTrialsWrite                      Permission = "admin:trials:write"
	AdminUsersPermissionsWrite            Permission = "admin:users:permissions:write"
	AdminUsersRead                        Permission = "admin:users:read"
	AdminUsersSignupApprovalsRead         Permission = "admin:users:signupApprovals:read"
	AdminUsersSignupApprovalsWrite        Permission = "admin:users:signupApprovals:write"
	AdminUsersWrite                       Permission = "admin:users:write"
	AdminVlmModelRead                     Permission = "admin:vlm:model:read"
	AdminVlmModelWrite                    Permission = "admin:vlm:model:write"
	ProjectsDataVersioningWrite           Permission = "projects:data:versioning:write"
	ProjectsLimitsWrite                   Permission = "projects:limits:write"
	ProjectsTrainingKerasWrite            Permission = "projects:training:keras:write"
	TestDataWrite                         Permission = "test:data:write"
	ThirdpartyauthRead                    Permission = "thirdpartyauth:read"
	ThirdpartyauthWrite                   Permission = "thirdpartyauth:write"
	UsersEmailsRead                       Permission = "users:emails:read"
	WhitelabelsRead                       Permission = "whitelabels:read"
	WhitelabelsWrite                      Permission = "whitelabels:write"
)

// Defines values for ProjectCategory.
const (
	ProjectCategoryAccelerometer   ProjectCategory = "Accelerometer"
	ProjectCategoryAudio           ProjectCategory = "Audio"
	ProjectCategoryImages          ProjectCategory = "Images"
	ProjectCategoryKeywordSpotting ProjectCategory = "Keyword spotting"
	ProjectCategoryObjectDetection ProjectCategory = "Object detection"
	ProjectCategoryOther           ProjectCategory = "Other"
)

// Defines values for ProjectInfoResponseAcquisitionSettingsViewType.
const (
	ProjectInfoResponseAcquisitionSettingsViewTypeGrid ProjectInfoResponseAcquisitionSettingsViewType = "grid"
	ProjectInfoResponseAcquisitionSettingsViewTypeList ProjectInfoResponseAcquisitionSettingsViewType = "list"
)

// Defines values for ProjectInfoResponseDeploySettingsSensor.
const (
	ProjectInfoResponseDeploySettingsSensorAccelerometer ProjectInfoResponseDeploySettingsSensor = "accelerometer"
	ProjectInfoResponseDeploySettingsSensorCamera        ProjectInfoResponseDeploySettingsSensor = "camera"
	ProjectInfoResponseDeploySettingsSensorEnvironmental ProjectInfoResponseDeploySettingsSensor = "environmental"
	ProjectInfoResponseDeploySettingsSensorFusion        ProjectInfoResponseDeploySettingsSensor = "fusion"
	ProjectInfoResponseDeploySettingsSensorMicrophone    ProjectInfoResponseDeploySettingsSensor = "microphone"
	ProjectInfoResponseDeploySettingsSensorPositional    ProjectInfoResponseDeploySettingsSensor = "positional"
	ProjectInfoResponseDeploySettingsSensorUnknown       ProjectInfoResponseDeploySettingsSensor = "unknown"
)

// Defines values for ProjectLabelingMethod.
const (
	LabelMap        ProjectLabelingMethod = "label_map"
	ObjectDetection ProjectLabelingMethod = "object_detection"
	SingleLabel     ProjectLabelingMethod = "single_label"
)

// Defines values for ProjectTierEnum.
const (
	ProjectTierEnumCommunityPlus ProjectTierEnum = "community-plus"
	ProjectTierEnumEnterprise    ProjectTierEnum = "enterprise"
	ProjectTierEnumFree          ProjectTierEnum = "free"
	ProjectTierEnumProfessional  ProjectTierEnum = "professional"
)

// Defines values for ProjectVisibility.
const (
	Private ProjectVisibility = "private"
	Public  ProjectVisibility = "public"
)

// Defines values for PublicProjectLicense.
const (
	Apache20        PublicProjectLicense = "Apache-2.0"
	BSD3Clause      PublicProjectLicense = "BSD-3-Clause"
	BSD3ClauseClear PublicProjectLicense = "BSD-3-Clause-Clear"
)

// Defines values for TargetConstraintsSelectedTargetBasedOn.
const (
	ConnectedDevice TargetConstraintsSelectedTargetBasedOn = "connected-device"
	Default         TargetConstraintsSelectedTargetBasedOn = "default"
	DefaultAccepted TargetConstraintsSelectedTargetBasedOn = "default-accepted"
	RecentProject   TargetConstraintsSelectedTargetBasedOn = "recent-project"
	UserConfigured  TargetConstraintsSelectedTargetBasedOn = "user-configured"
)

// Defines values for TutorialType.
const (
	Cv  TutorialType = "cv"
	Kws TutorialType = "kws"
)

// Defines values for UpdateProjectRequestDataAcquisitionViewType.
const (
	UpdateProjectRequestDataAcquisitionViewTypeGrid UpdateProjectRequestDataAcquisitionViewType = "grid"
	UpdateProjectRequestDataAcquisitionViewTypeList UpdateProjectRequestDataAcquisitionViewType = "list"
)

// Defines values for UpdateProjectRequestSelectedProjectTypeInWizard.
const (
	UpdateProjectRequestSelectedProjectTypeInWizardAccelerometer       UpdateProjectRequestSelectedProjectTypeInWizard = "accelerometer"
	UpdateProjectRequestSelectedProjectTypeInWizardAudio               UpdateProjectRequestSelectedProjectTypeInWizard = "audio"
	UpdateProjectRequestSelectedProjectTypeInWizardImageClassification UpdateProjectRequestSelectedProjectTypeInWizard = "image_classification"
	UpdateProjectRequestSelectedProjectTypeInWizardObjectDetection     UpdateProjectRequestSelectedProjectTypeInWizard = "object_detection"
	UpdateProjectRequestSelectedProjectTypeInWizardSomethingElse       UpdateProjectRequestSelectedProjectTypeInWizard = "something_else"
)

// Defines values for UserTierEnum.
const (
	UserTierEnumCommunityPlus UserTierEnum = "community-plus"
	UserTierEnumEnterprise    UserTierEnum = "enterprise"
	UserTierEnumFree          UserTierEnum = "free"
	UserTierEnumProfessional  UserTierEnum = "professional"
)

// ApplicationBudget Specifies limits for your specific application, as available RAM and ROM for the model's operation and the maximum allowed latency.
type ApplicationBudget struct {
	// EnergyPerInferenceJoules Describes range of expected availability for an arbitrary resource
	EnergyPerInferenceJoules *ResourceRange `json:"energyPerInferenceJoules,omitempty"`

	// LatencyPerInferenceMs Describes range of expected availability for an arbitrary resource
	LatencyPerInferenceMs *ResourceRange `json:"latencyPerInferenceMs,omitempty"`

	// MemoryOverhead RAM and ROM specifications of target
	MemoryOverhead *TargetMemory `json:"memoryOverhead,omitempty"`
}

// BuildOnDeviceModelRequest defines model for BuildOnDeviceModelRequest.
type BuildOnDeviceModelRequest struct {
	Engine    DeploymentTargetEngine `json:"engine"`
	ModelType *KerasModelTypeEnum    `json:"modelType,omitempty"`

	// Parameters List of custom parameters for this deployment job (see the list of parameters that the block exposes in DeploymentTarget#parameters).
	Parameters *map[string]string `json:"parameters,omitempty"`
}

// CreatedUpdatedByUser defines model for CreatedUpdatedByUser.
type CreatedUpdatedByUser struct {
	Id       int     `json:"id"`
	Name     string  `json:"name"`
	Photo    *string `json:"photo,omitempty"`
	Username string  `json:"username"`
}

// DeploymentTargetEngine defines model for DeploymentTargetEngine.
type DeploymentTargetEngine string

// DevelopmentKeys defines model for DevelopmentKeys.
type DevelopmentKeys struct {
	// ApiKey API Key
	ApiKey *string `json:"apiKey,omitempty"`

	// HmacKey HMAC Key
	HmacKey *string `json:"hmacKey,omitempty"`
}

// Device defines model for Device.
type Device struct {
	Created time.Time `json:"created"`

	// DeviceId Unique identifier (such as MAC address) for a device
	DeviceId   string `json:"deviceId"`
	DeviceType string `json:"deviceType"`
	Id         int    `json:"id"`

	// InferenceInfo If `remoteMgmtMode` is set to `inference` this object shows information about the model that's ran on device.
	InferenceInfo *struct {
		DeployedVersion int                           `json:"deployedVersion"`
		ModelType       *DeviceInferenceInfoModelType `json:"modelType,omitempty"`
		ProjectId       int                           `json:"projectId"`
		ProjectName     string                        `json:"projectName"`
		ProjectOwner    string                        `json:"projectOwner"`
	} `json:"inferenceInfo,omitempty"`

	// LastSeen Last message that was received from the device (ignoring keep-alive)
	LastSeen time.Time `json:"lastSeen"`
	Name     string    `json:"name"`

	// RemoteMgmtMode Replaces `remote_mgmt_connected`. Shows whether the device is connected to the remote management interface, and in which mode.
	RemoteMgmtMode DeviceRemoteMgmtMode `json:"remoteMgmtMode"`

	// RemoteMgmtConnected Whether the device is connected to the remote management interface. This property is deprecated, use `remoteMgmtMode` instead.
	RemoteMgmtConnected bool `json:"remote_mgmt_connected"`

	// RemoteMgmtHost The remote management host that the device is connected to
	RemoteMgmtHost *string `json:"remote_mgmt_host,omitempty"`
	Sensors        []struct {
		// Frequencies Supported frequencies for this sensor in Hz.
		Frequencies []float32 `json:"frequencies"`

		// MaxSampleLengthS Maximum supported sample length in seconds
		MaxSampleLengthS int    `json:"maxSampleLengthS"`
		Name             string `json:"name"`
	} `json:"sensors"`
	SupportsSnapshotStreaming bool `json:"supportsSnapshotStreaming"`
}

// DeviceInferenceInfoModelType defines model for Device.InferenceInfo.ModelType.
type DeviceInferenceInfoModelType string

// DeviceRemoteMgmtMode Replaces `remote_mgmt_connected`. Shows whether the device is connected to the remote management interface, and in which mode.
type DeviceRemoteMgmtMode string

// GenericApiResponse defines model for GenericApiResponse.
type GenericApiResponse struct {
	// Error Optional error description (set if 'success' was false)
	Error *string `json:"error,omitempty"`

	// Success Whether the operation succeeded
	Success bool `json:"success"`
}

// GetDeploymentResponse defines model for GetDeploymentResponse.
type GetDeploymentResponse struct {
	// Error Optional error description (set if 'success' was false)
	Error         *string `json:"error,omitempty"`
	HasDeployment bool    `json:"hasDeployment"`

	// Success Whether the operation succeeded
	Success bool `json:"success"`
	Version *int `json:"version,omitempty"`
}

// GetJWTRequest defines model for GetJWTRequest.
type GetJWTRequest struct {
	// Password Password
	Password string `json:"password"`

	// SessionId Session ID
	SessionId *string               `json:"sessionId,omitempty"`
	SsoType   *GetJWTRequestSsoType `json:"ssoType,omitempty"`

	// TotpToken TOTP Token. Required if a user has multi-factor authentication with a TOTP token enabled. If a user has MFA enabled, but no totpToken is submitted; then an error starting with "ERR_TOTP_TOKEN IS REQUIRED" is returned. Use this to then prompt for an MFA token and re-login.
	TotpToken *string `json:"totpToken,omitempty"`

	// Username Username or e-mail address
	Username string `json:"username"`

	// Uuid Evaluation user UUID
	Uuid *string `json:"uuid,omitempty"`
}

// GetJWTRequestSsoType defines model for GetJWTRequest.SsoType.
type GetJWTRequestSsoType string

// GetJWTResponse defines model for GetJWTResponse.
type GetJWTResponse struct {
	// Error Optional error description (set if 'success' was false)
	Error *string `json:"error,omitempty"`

	// RedirectUrl Redirect URL to follow to complete login
	RedirectUrl *string `json:"redirectUrl,omitempty"`

	// Success Whether the operation succeeded
	Success bool `json:"success"`

	// Token JWT token, to be used to log in in the future through JWTAuthentication
	Token *string `json:"token,omitempty"`
}

// GetJobResponse defines model for GetJobResponse.
type GetJobResponse struct {
	// Error Optional error description (set if 'success' was false)
	Error *string `json:"error,omitempty"`
	Job   Job     `json:"job"`

	// Success Whether the operation succeeded
	Success bool `json:"success"`
}

// Job defines model for Job.
type Job struct {
	// AdditionalInfo Additional metadata associated with this job.
	AdditionalInfo *string `json:"additionalInfo,omitempty"`

	// Category User-friendly category (e.g. "Training model")
	Category string `json:"category"`

	// CategoryCount Some job categories keep a counter on the job number, e.g. in synthetic data, so we know what the 1st, 2nd etc. job was in the UI.
	CategoryCount *int `json:"categoryCount,omitempty"`

	// CategoryKey Machine-readable category (e.g. "learn-train-studio-wrapper")
	CategoryKey string `json:"categoryKey"`

	// ComputeTime Job duration time in seconds from start to finished, measured by k8s job watcher.
	ComputeTime *float32 `json:"computeTime,omitempty"`

	// Created When the job was created.
	Created       time.Time             `json:"created"`
	CreatedByUser *CreatedUpdatedByUser `json:"createdByUser,omitempty"`

	// Finished When the job was finished.
	Finished *time.Time `json:"finished,omitempty"`

	// FinishedSuccessful Whether the job finished successfully.
	FinishedSuccessful *bool `json:"finishedSuccessful,omitempty"`

	// Id Job id, use this to refer back to the job. The web socket API also uses this ID.
	Id int `json:"id"`

	// JobNotificationUids The IDs of users who should be notified when a job is finished.
	JobNotificationUids []int `json:"jobNotificationUids"`

	// Key External job identifier, this can be used to categorize jobs, and recover job status. E.g. set this to 'keras-192' for a Keras learning block with ID 192. When a user refreshes the page you can check whether a job is active for this ID and re-attach.
	Key string `json:"key"`

	// Metadata Structured job metadata
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// Started When the job was started.
	Started *time.Time `json:"started,omitempty"`
}

// KerasModelTypeEnum defines model for KerasModelTypeEnum.
type KerasModelTypeEnum string

// KerasModelVariantEnum defines model for KerasModelVariantEnum.
type KerasModelVariantEnum string

// LatencyDevice defines model for LatencyDevice.
type LatencyDevice struct {
	Float32ConvLatency float32 `json:"float32ConvLatency"`
	Float32Latency     float32 `json:"float32Latency"`
	HelpText           string  `json:"helpText"`
	Int8ConvLatency    float32 `json:"int8ConvLatency"`
	Int8Latency        float32 `json:"int8Latency"`
	Mcu                string  `json:"mcu"`
	Name               string  `json:"name"`
	Selected           bool    `json:"selected"`
}

// MemorySpec Describes performance characteristics of a particular memory type
type MemorySpec struct {
	// FastBytes Describes range of expected availability for an arbitrary resource
	FastBytes *ResourceRange `json:"fastBytes,omitempty"`

	// SlowBytes Describes range of expected availability for an arbitrary resource
	SlowBytes *ResourceRange `json:"slowBytes,omitempty"`
}

// ModelEngineShortEnum defines model for ModelEngineShortEnum.
type ModelEngineShortEnum string

// Permission defines model for Permission.
type Permission string

// Project defines model for Project.
type Project struct {
	// AllowsLivePublicAccess Whether this project allows live, public access. Unlike a public version, a live public project is not fixed in time, and always includes the latest project changes. Similar to public versions, a live public project can be cloned by anyone, creating a new, separate project.
	AllowsLivePublicAccess bool `json:"allowsLivePublicAccess"`

	// Category Project category
	Category               *ProjectCategory      `json:"category,omitempty"`
	Collaborators          []ProjectCollaborator `json:"collaborators"`
	Created                time.Time             `json:"created"`
	DataExplorerScreenshot *string               `json:"dataExplorerScreenshot,omitempty"`
	DeletedDate            *time.Time            `json:"deletedDate,omitempty"`
	Description            string                `json:"description"`

	// DeveloperProfileUserId User ID of the developer profile, if any.
	DeveloperProfileUserId *int       `json:"developerProfileUserId,omitempty"`
	FullDeletionDate       *time.Time `json:"fullDeletionDate,omitempty"`

	// HasPublicVersion Whether this project has been published or not.
	HasPublicVersion          bool `json:"hasPublicVersion"`
	Id                        int  `json:"id"`
	IndPauseProcessingSamples bool `json:"indPauseProcessingSamples"`

	// IsEnterpriseProject Whether this is an enterprise project
	IsEnterpriseProject bool `json:"isEnterpriseProject"`

	// IsPublic Whether this is a public version of a project. A version is a snapshot of a project at a certain point in time, which can be used to periodically save the state of a project. Versions can be private (just for internal use and reference) or public, available to everyone. A public version can be cloned by anyone, restoring the state of the project at the time into a new, separate project.
	IsPublic       bool                  `json:"isPublic"`
	LabelingMethod ProjectLabelingMethod `json:"labelingMethod"`
	LastAccessed   *time.Time            `json:"lastAccessed,omitempty"`

	// LastModificationDetails Details about the last modification
	LastModificationDetails *string               `json:"lastModificationDetails,omitempty"`
	LastModified            *time.Time            `json:"lastModified,omitempty"`
	License                 *PublicProjectLicense `json:"license,omitempty"`

	// Logo Custom logo for this project (not available for all projects)
	Logo *string `json:"logo,omitempty"`

	// Metadata Metadata about the project
	Metadata map[string]interface{} `json:"metadata"`
	Name     string                 `json:"name"`

	// Owner User or organization that owns the project
	Owner string `json:"owner"`

	// OwnerAvatar URL of the project owner avatar, if any.
	OwnerAvatar             *string `json:"ownerAvatar,omitempty"`
	OwnerIsDeveloperProfile bool    `json:"ownerIsDeveloperProfile"`
	OwnerOrganizationId     *int    `json:"ownerOrganizationId,omitempty"`
	OwnerUserId             *int    `json:"ownerUserId,omitempty"`

	// PublicProjectListed If the project allows public access, whether to list it the public projects overview response. If not listed, the project is still accessible via direct link. If the project does not allow public access, this field has no effect.
	PublicProjectListed       bool       `json:"publicProjectListed"`
	ScheduledFullDeletionDate *time.Time `json:"scheduledFullDeletionDate,omitempty"`

	// Tags List of project tags
	Tags *[]string `json:"tags,omitempty"`

	// Tier The project tier. This is "enterprise" for all organization projects, or the user tier for all user projects.
	Tier ProjectTierEnum `json:"tier"`

	// WhitelabelId Unique identifier of the white label this project belongs to, if any.
	WhitelabelId *int `json:"whitelabelId"`

	// WhitelabelName Name of the white label this project belongs to, if any.
	WhitelabelName *string `json:"whitelabelName,omitempty"`
}

// ProjectCategory Project category
type ProjectCategory string

// ProjectCollaborator defines model for ProjectCollaborator.
type ProjectCollaborator struct {
	// Activated Whether the user has activated their account or not.
	Activated   bool      `json:"activated"`
	CompanyName *string   `json:"companyName,omitempty"`
	Created     time.Time `json:"created"`
	Email       string    `json:"email"`

	// HasPendingPayments Whether the user has pending payments.
	HasPendingPayments *bool `json:"hasPendingPayments,omitempty"`
	Id                 int   `json:"id"`

	// Idps List of identity providers (e.g. Google, GitHub) that the user has used to sign in with
	Idps     *[]string  `json:"idps,omitempty"`
	IsOwner  bool       `json:"isOwner"`
	JobTitle *string    `json:"jobTitle,omitempty"`
	LastSeen *time.Time `json:"lastSeen,omitempty"`

	// MfaConfigured Whether the user has configured multi-factor authentication
	MfaConfigured bool   `json:"mfaConfigured"`
	Name          string `json:"name"`
	Pending       bool   `json:"pending"`

	// Permissions List of permissions the user has
	Permissions *[]Permission `json:"permissions,omitempty"`
	Photo       *string       `json:"photo,omitempty"`
	StaffInfo   StaffInfo     `json:"staffInfo"`

	// StripeCustomerId Stripe customer ID, if any.
	StripeCustomerId *string `json:"stripeCustomerId,omitempty"`

	// Tier The user account tier.
	Tier     *UserTierEnum `json:"tier,omitempty"`
	Username string        `json:"username"`
}

// ProjectDataSummary defines model for ProjectDataSummary.
type ProjectDataSummary struct {
	DataCount int `json:"dataCount"`

	// Labels Labels in the training set
	Labels []string `json:"labels"`

	// TotalLengthMs Total length (in ms.) of all data in the training set
	TotalLengthMs float32 `json:"totalLengthMs"`
}

// ProjectInfoResponse defines model for ProjectInfoResponse.
type ProjectInfoResponse struct {
	AcquisitionSettings struct {
		// DefaultPageSize Default page size on data acquisition
		DefaultPageSize int `json:"defaultPageSize"`

		// GridColumnCount Number of grid columns in non-detailed view
		GridColumnCount int `json:"gridColumnCount"`

		// GridColumnCountDetailed Number of grid columns in detailed view
		GridColumnCountDetailed int `json:"gridColumnCountDetailed"`

		// InlineEditBoundingBoxes If enabled, allows editing bounding box labels directly from the acquisition UI.
		InlineEditBoundingBoxes bool `json:"inlineEditBoundingBoxes"`

		// IntervalMs Interval during the last acquisition, or the recommended interval based on the data set.
		IntervalMs float32 `json:"intervalMs"`

		// Label Label that was used during the last acquisition.
		Label *string `json:"label,omitempty"`

		// LengthMs Length of the last acquisition, or a recommended interval based on the data set.
		LengthMs int `json:"lengthMs"`

		// SegmentLength Length of the last sample segment after segmenting a larger sample.
		SegmentLength *float32 `json:"segmentLength,omitempty"`

		// SegmentShift Whether to auto-shift segments
		SegmentShift bool `json:"segmentShift"`

		// Sensor Sensor that was used during the last acquisition.
		Sensor *string `json:"sensor,omitempty"`

		// ShowExactSampleLength If enabled, does not round sample length to hours/minutes/seconds, but always displays sample length in milliseconds. E.g. instead of 1m 32s, this'll say 92,142ms.
		ShowExactSampleLength bool `json:"showExactSampleLength"`

		// ViewType Default view type on data acquisition
		ViewType ProjectInfoResponseAcquisitionSettingsViewType `json:"viewType"`
	} `json:"acquisitionSettings"`
	Collaborators []User `json:"collaborators"`
	ComputeTime   struct {
		// PeriodEndDate End of the current time period. This is the date when the compute time resets again.
		PeriodEndDate time.Time `json:"periodEndDate"`

		// PeriodStartDate Start of the current time period.
		PeriodStartDate time.Time `json:"periodStartDate"`

		// TimeLeftMs The amount of compute left for the current time period.
		TimeLeftMs int `json:"timeLeftMs"`

		// TimeUsedMs The amount of compute used for the current time period.
		TimeUsedMs int `json:"timeUsedMs"`
	} `json:"computeTime"`

	// CsvImportConfig Config file specifying how to process CSV files.
	CsvImportConfig        *map[string]interface{} `json:"csvImportConfig,omitempty"`
	DataSummary            ProjectDataSummary      `json:"dataSummary"`
	DataSummaryPerCategory struct {
		PostProcessing ProjectDataSummary `json:"postProcessing"`
		Testing        ProjectDataSummary `json:"testing"`
		Training       ProjectDataSummary `json:"training"`
	} `json:"dataSummaryPerCategory"`

	// DefaultImpulseId Default selected impulse (by ID).
	DefaultImpulseId *int `json:"defaultImpulseId,omitempty"`
	DeploySettings   struct {
		ArduinoLibraryName    string                                  `json:"arduinoLibraryName"`
		EonCompiler           bool                                    `json:"eonCompiler"`
		LastDeployModelEngine *ModelEngineShortEnum                   `json:"lastDeployModelEngine,omitempty"`
		ParticleLibraryName   string                                  `json:"particleLibraryName"`
		Sensor                ProjectInfoResponseDeploySettingsSensor `json:"sensor"`
		TinkergenLibraryName  string                                  `json:"tinkergenLibraryName"`
	} `json:"deploySettings"`
	DevelopmentKeys DevelopmentKeys `json:"developmentKeys"`
	Devices         []Device        `json:"devices"`

	// DspJobNotificationUids The IDs of users who should be notified when a DSP job is finished.
	DspJobNotificationUids []int `json:"dspJobNotificationUids"`
	DspPageSize            *int  `json:"dspPageSize,omitempty"`

	// Error Optional error description (set if 'success' was false)
	Error *string `json:"error,omitempty"`

	// Experiments Experiments that the project has access to. Enabling experiments can only be done through a JWT token.
	Experiments []struct {
		Enabled    bool    `json:"enabled"`
		Help       *string `json:"help,omitempty"`
		ShowToUser bool    `json:"showToUser"`
		Title      string  `json:"title"`
		Type       string  `json:"type"`
	} `json:"experiments"`

	// ExportJobNotificationUids The IDs of users who should be notified when an export job is finished.
	ExportJobNotificationUids []int `json:"exportJobNotificationUids"`
	HasNewTrainingData        bool  `json:"hasNewTrainingData"`
	Impulse                   struct {
		// Complete Whether an impulse was fully trained and configured
		Complete bool `json:"complete"`

		// Configured Whether an impulse was configured
		Configured bool `json:"configured"`

		// Created Whether an impulse was created
		Created bool `json:"created"`
	} `json:"impulse"`

	// InPretrainedModelFlow DEPRECATED. To enable the pretrained model flow, set the impulse type property to "BYOM" instead.
	InPretrainedModelFlow bool                  `json:"inPretrainedModelFlow"`
	LastShownModelEngine  *ModelEngineShortEnum `json:"lastShownModelEngine,omitempty"`
	LatencyDevices        []LatencyDevice       `json:"latencyDevices"`

	// ModelTestingJobNotificationUids The IDs of users who should be notified when a model testing job is finished.
	ModelTestingJobNotificationUids []int `json:"modelTestingJobNotificationUids"`

	// Notifications List of notifications to show within the project
	Notifications []string `json:"notifications"`
	Performance   struct {
		// DspFileSizeMb Maximum size for DSP file output
		DspFileSizeMb         int  `json:"dspFileSizeMb"`
		EnterprisePerformance bool `json:"enterprisePerformance"`
		Gpu                   bool `json:"gpu"`

		// JobLimitM Compute time limit per job in minutes (applies only to DSP and learning jobs).
		JobLimitM int `json:"jobLimitM"`

		// TrainJobRamMb Amount of RAM allocated to training jobs
		TrainJobRamMb int `json:"trainJobRamMb"`
	} `json:"performance"`
	Project Project `json:"project"`

	// Readme Present if a readme is set for this project
	Readme *struct {
		Html     string `json:"html"`
		Markdown string `json:"markdown"`
	} `json:"readme,omitempty"`
	ShowCreateFirstImpulse   bool `json:"showCreateFirstImpulse"`
	ShowGettingStartedWizard struct {
		// Classes Classes or labels used in the getting started wizard
		Classes    *[]string `json:"classes,omitempty"`
		ShowWizard bool      `json:"showWizard"`

		// Step Current step of the getting started wizard
		Step int `json:"step"`

		// Tutorial The type of in-product guided tutorial to show in the getting started wizard
		Tutorial *TutorialType `json:"tutorial,omitempty"`
	} `json:"showGettingStartedWizard"`

	// ShowSensorDataInAcquisitionGraph Whether to show the actual sensor data in acquisition charts (only applies when you have structured labels)
	ShowSensorDataInAcquisitionGraph bool   `json:"showSensorDataInAcquisitionGraph"`
	StudioUrl                        string `json:"studioUrl"`

	// Success Whether the operation succeeded
	Success           bool               `json:"success"`
	TargetConstraints *TargetConstraints `json:"targetConstraints,omitempty"`

	// TrainJobNotificationUids The IDs of users who should be notified when a Keras or retrain job is finished.
	TrainJobNotificationUids []int `json:"trainJobNotificationUids"`
	Urls                     struct {
		// MobileClient Base URL for the mobile client. If this is undefined then no development API key is set.
		MobileClient *string `json:"mobileClient,omitempty"`

		// MobileClientComputer Base URL for collecting data with the mobile client from a computer. If this is undefined then no development API key is set.
		MobileClientComputer *string `json:"mobileClientComputer,omitempty"`

		// MobileClientInference Base URL for running inference with the mobile client. If this is undefined then no development API key is set.
		MobileClientInference *string `json:"mobileClientInference,omitempty"`
	} `json:"urls"`
	VersioningStorageSizeMib *int `json:"versioningStorageSizeMib,omitempty"`
}

// ProjectInfoResponseAcquisitionSettingsViewType Default view type on data acquisition
type ProjectInfoResponseAcquisitionSettingsViewType string

// ProjectInfoResponseDeploySettingsSensor defines model for ProjectInfoResponse.DeploySettings.Sensor.
type ProjectInfoResponseDeploySettingsSensor string

// ProjectLabelingMethod defines model for ProjectLabelingMethod.
type ProjectLabelingMethod string

// ProjectTierEnum The project tier. This is "enterprise" for all organization projects, or the user tier for all user projects.
type ProjectTierEnum string

// ProjectVisibility The visibility of the project, either public or private. Public projects can be viewed by anyone on the internet and edited by collaborators. Private projects can only be viewed and edited by collaborators.
type ProjectVisibility string

// PublicProjectLicense defines model for PublicProjectLicense.
type PublicProjectLicense string

// ResourceRange Describes range of expected availability for an arbitrary resource
type ResourceRange struct {
	Maximum *float32 `json:"maximum,omitempty"`
	Minimum *float32 `json:"minimum,omitempty"`
}

// StaffInfo defines model for StaffInfo.
type StaffInfo struct {
	CompanyName   *string `json:"companyName,omitempty"`
	HasSudoRights bool    `json:"hasSudoRights"`
	IsStaff       bool    `json:"isStaff"`
}

// StartJobResponse defines model for StartJobResponse.
type StartJobResponse struct {
	// Error Optional error description (set if 'success' was false)
	Error *string `json:"error,omitempty"`

	// Id Job identifier. Status updates will include this identifier.
	Id int `json:"id"`

	// Success Whether the operation succeeded
	Success bool `json:"success"`
}

// TargetConstraints defines model for TargetConstraints.
type TargetConstraints struct {
	// ApplicationBudgets A list of application budgets to be configured based on target device. An application budget enables guidance on performance and resource usage. The first application budget in the list is considered as the selected budget for the project.
	ApplicationBudgets []ApplicationBudget `json:"applicationBudgets"`

	// SelectedTargetBasedOn A type explaining how the target was chosen. If updating this manually, use the 'user-configured' type
	SelectedTargetBasedOn *TargetConstraintsSelectedTargetBasedOn `json:"selectedTargetBasedOn,omitempty"`

	// TargetDevices The potential targets for the project, where each entry captures hardware attributes that allow target guidance throughout the Studio workflow. The first target in the list is considered as the selected target for the project.
	TargetDevices []TargetConstraintsDevice `json:"targetDevices"`
}

// TargetConstraintsSelectedTargetBasedOn A type explaining how the target was chosen. If updating this manually, use the 'user-configured' type
type TargetConstraintsSelectedTargetBasedOn string

// TargetConstraintsDevice defines model for TargetConstraintsDevice.
type TargetConstraintsDevice struct {
	// Board The exact dev board part number, if available
	Board *string `json:"board,omitempty"`

	// LatencyDevice MCU identifier, if available
	LatencyDevice *string `json:"latencyDevice,omitempty"`

	// Name Display name in Studio
	Name *string `json:"name,omitempty"`

	// Processors Target processors
	Processors *[]TargetProcessor `json:"processors,omitempty"`
}

// TargetMemory RAM and ROM specifications of target
type TargetMemory struct {
	// Ram Describes performance characteristics of a particular memory type
	Ram *MemorySpec `json:"ram,omitempty"`

	// Rom Describes performance characteristics of a particular memory type
	Rom *MemorySpec `json:"rom,omitempty"`
}

// TargetProcessor defines model for TargetProcessor.
type TargetProcessor struct {
	// Accelerator Target accelerator, if any
	Accelerator *string `json:"accelerator,omitempty"`

	// Architecture Processor family, informing about the processor's instruction set and core design
	Architecture *string `json:"architecture,omitempty"`

	// ClockRateMhz Describes range of expected availability for an arbitrary resource
	ClockRateMhz *ResourceRange `json:"clockRateMhz,omitempty"`

	// Format Processor type, serving as a broad descriptor for the intended use-case
	Format *string `json:"format,omitempty"`

	// Fpu Does the target processor have a floating point unit
	Fpu *bool `json:"fpu,omitempty"`

	// Memory RAM and ROM specifications of target
	Memory *TargetMemory `json:"memory,omitempty"`

	// Part The exact part number, if available
	Part *string `json:"part,omitempty"`

	// SpecificArchitecture Processor architecture, informing about the specific processor, if known
	SpecificArchitecture *string `json:"specificArchitecture,omitempty"`
}

// TutorialType The type of in-product guided tutorial to show in the getting started wizard
type TutorialType string

// UpdateProjectRequest Only fields set in this object will be updated.
type UpdateProjectRequest struct {
	// AiActionsGridColumnCount Number of grid columns in AI Actions
	AiActionsGridColumnCount *int `json:"aiActionsGridColumnCount,omitempty"`

	// ComputeTimeLimitM Job limit in minutes
	ComputeTimeLimitM *int `json:"computeTimeLimitM,omitempty"`

	// CsvImportConfig Config file specifying how to process CSV files. (set to null to clear the config)
	CsvImportConfig *map[string]interface{} `json:"csvImportConfig,omitempty"`

	// DataAcquisitionGridColumnCount Number of grid columns in non-detailed view on data acquisition
	DataAcquisitionGridColumnCount *int `json:"dataAcquisitionGridColumnCount,omitempty"`

	// DataAcquisitionGridColumnCountDetailed Number of grid columns in detailed view on data acquisition
	DataAcquisitionGridColumnCountDetailed *int `json:"dataAcquisitionGridColumnCountDetailed,omitempty"`

	// DataAcquisitionPageSize Default page size on data acquisition
	DataAcquisitionPageSize *int `json:"dataAcquisitionPageSize,omitempty"`

	// DataAcquisitionViewType Default view type on data acquisition
	DataAcquisitionViewType *UpdateProjectRequestDataAcquisitionViewType `json:"dataAcquisitionViewType,omitempty"`
	DefaultProfilingVariant *KerasModelVariantEnum                       `json:"defaultProfilingVariant,omitempty"`
	Description             *string                                      `json:"description,omitempty"`

	// DspFileSizeMb DSP file size in MB
	DspFileSizeMb *int `json:"dspFileSizeMb,omitempty"`

	// DspJobNotificationUids The IDs of users who should be notified when a DSP job is finished.
	DspJobNotificationUids *[]int `json:"dspJobNotificationUids,omitempty"`

	// DspPageSize Set to '0' to disable DSP paging
	DspPageSize *int `json:"dspPageSize,omitempty"`

	// EnabledModelProfilingVariants Set of model variants enabled by default on the model testing and live classification pages.
	EnabledModelProfilingVariants *[]KerasModelVariantEnum `json:"enabledModelProfilingVariants,omitempty"`
	EnterprisePerformance         *bool                    `json:"enterprisePerformance,omitempty"`
	Experiments                   *[]string                `json:"experiments,omitempty"`

	// ExportJobNotificationUids The IDs of users who should be notified when an export job is finished.
	ExportJobNotificationUids *[]int `json:"exportJobNotificationUids,omitempty"`

	// GettingStartedClasses Classes or labels used in the getting started wizard
	GettingStartedClasses *[]string `json:"gettingStartedClasses,omitempty"`

	// GettingStartedStep The next step in the getting started wizard, or set to -1 to clear the getting started wizard
	GettingStartedStep *int `json:"gettingStartedStep,omitempty"`

	// GettingStartedTutorial The type of in-product guided tutorial to show in the getting started wizard
	GettingStartedTutorial *TutorialType `json:"gettingStartedTutorial,omitempty"`

	// ImpulseListAdditionalMetricsShownColumns Which additional metrics should be shown in the impulse list. See 'GetAllDetailedImpulsesResponse' for a list of all metrics.
	ImpulseListAdditionalMetricsShownColumns *[]string `json:"impulseListAdditionalMetricsShownColumns,omitempty"`

	// ImpulseListCoreMetricsHiddenColumns Which core metrics should be hidden in the impulse list. See 'GetAllDetailedImpulsesResponse' for a list of all metrics.
	ImpulseListCoreMetricsHiddenColumns *[]string `json:"impulseListCoreMetricsHiddenColumns,omitempty"`

	// ImpulseListExtraColumns Which extra columns should be shown in the impulse list.
	ImpulseListExtraColumns *[]string `json:"impulseListExtraColumns,omitempty"`

	// InPretrainedModelFlow DEPRECATED. To enable the pretrained model flow, set the impulse type property to "BYOM" instead.
	InPretrainedModelFlow *bool `json:"inPretrainedModelFlow,omitempty"`

	// IndPauseProcessingSamples Used in tests, to ensure samples that need to be processed async are not picked up until the flag is set to FALSE again.
	IndPauseProcessingSamples *bool `json:"indPauseProcessingSamples,omitempty"`

	// InlineEditBoundingBoxes If enabled, allows editing bounding box labels directly from the acquisition UI.
	InlineEditBoundingBoxes *bool                  `json:"inlineEditBoundingBoxes,omitempty"`
	LabelingMethod          *ProjectLabelingMethod `json:"labelingMethod,omitempty"`
	LastAcquisitionLabel    *string                `json:"lastAcquisitionLabel,omitempty"`

	// LastDeployEonCompiler Call this when clicking the Eon compiler setting
	LastDeployEonCompiler *bool                 `json:"lastDeployEonCompiler,omitempty"`
	LastDeployModelEngine *ModelEngineShortEnum `json:"lastDeployModelEngine,omitempty"`

	// LastDeploymentTarget Which deployment target was last selected (used to populate this deployment target again the next time you visit the deployment page). Should match the _format_ property of the response from listDeploymentTargetsForProject.
	LastDeploymentTarget *string               `json:"lastDeploymentTarget,omitempty"`
	LastShownModelEngine *ModelEngineShortEnum `json:"lastShownModelEngine,omitempty"`

	// LatencyDevice MCU used for calculating latency
	LatencyDevice *string `json:"latencyDevice,omitempty"`

	// Logo New logo URL, or set to `null` to remove the logo.
	Logo *string `json:"logo,omitempty"`

	// Metadata New metadata about the project
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// ModelTestingJobNotificationUids The IDs of users who should be notified when a model testing job is finished.
	ModelTestingJobNotificationUids *[]int `json:"modelTestingJobNotificationUids,omitempty"`

	// Name New project name.
	Name *string `json:"name,omitempty"`

	// ProjectVisibility The visibility of the project, either public or private. Public projects can be viewed by anyone on the internet and edited by collaborators. Private projects can only be viewed and edited by collaborators.
	ProjectVisibility *ProjectVisibility `json:"projectVisibility,omitempty"`

	// PublicProjectListed If the project allows public access, whether to list it the public projects overview response. If not listed, the project is still accessible via direct link. If the project does not allow public access, this field has no effect.
	PublicProjectListed *bool `json:"publicProjectListed,omitempty"`

	// Readme Readme for the project (in Markdown)
	Readme *string `json:"readme,omitempty"`

	// SelectedProjectTypeInWizard Which option was selected in the project type wizard
	SelectedProjectTypeInWizard *UpdateProjectRequestSelectedProjectTypeInWizard `json:"selectedProjectTypeInWizard,omitempty"`

	// ShowCreateFirstImpulse Whether to show the 'Create your first impulse' section on the dashboard
	ShowCreateFirstImpulse *bool `json:"showCreateFirstImpulse,omitempty"`

	// ShowExactSampleLength If enabled, does not round sample length to hours/minutes/seconds, but always displays sample length in milliseconds. E.g. instead of 1m 32s, this'll say 92,142ms.
	ShowExactSampleLength *bool `json:"showExactSampleLength,omitempty"`

	// ShowSensorDataInAcquisitionGraph Whether to show the actual sensor data in acquisition charts (only applies when you have structured labels)
	ShowSensorDataInAcquisitionGraph *bool `json:"showSensorDataInAcquisitionGraph,omitempty"`

	// TrainJobNotificationUids The IDs of users who should be notified when a Keras or retrain job is finished.
	TrainJobNotificationUids *[]int `json:"trainJobNotificationUids,omitempty"`

	// TrainJobRamMb Amount of RAM allocated to training jobs
	TrainJobRamMb *int `json:"trainJobRamMb,omitempty"`

	// UseGpu Whether to use GPU for training
	UseGpu                   *bool `json:"useGpu,omitempty"`
	VersioningStorageSizeMib *int  `json:"versioningStorageSizeMib,omitempty"`
}

// UpdateProjectRequestDataAcquisitionViewType Default view type on data acquisition
type UpdateProjectRequestDataAcquisitionViewType string

// UpdateProjectRequestSelectedProjectTypeInWizard Which option was selected in the project type wizard
type UpdateProjectRequestSelectedProjectTypeInWizard string

// User defines model for User.
type User struct {
	// Activated Whether the user has activated their account or not.
	Activated   bool      `json:"activated"`
	CompanyName *string   `json:"companyName,omitempty"`
	Created     time.Time `json:"created"`
	Email       string    `json:"email"`

	// HasPendingPayments Whether the user has pending payments.
	HasPendingPayments *bool `json:"hasPendingPayments,omitempty"`
	Id                 int   `json:"id"`

	// Idps List of identity providers (e.g. Google, GitHub) that the user has used to sign in with
	Idps     *[]string  `json:"idps,omitempty"`
	JobTitle *string    `json:"jobTitle,omitempty"`
	LastSeen *time.Time `json:"lastSeen,omitempty"`

	// MfaConfigured Whether the user has configured multi-factor authentication
	MfaConfigured bool   `json:"mfaConfigured"`
	Name          string `json:"name"`
	Pending       bool   `json:"pending"`

	// Permissions List of permissions the user has
	Permissions *[]Permission `json:"permissions,omitempty"`
	Photo       *string       `json:"photo,omitempty"`
	StaffInfo   StaffInfo     `json:"staffInfo"`

	// StripeCustomerId Stripe customer ID, if any.
	StripeCustomerId *string `json:"stripeCustomerId,omitempty"`

	// Tier The user account tier.
	Tier     *UserTierEnum `json:"tier,omitempty"`
	Username string        `json:"username"`
}

// UserTierEnum The user account tier.
type UserTierEnum string

// DeploymentTypeParameter defines model for DeploymentTypeParameter.
type DeploymentTypeParameter = string

// JobIdParameter defines model for JobIdParameter.
type JobIdParameter = int

// ModelEngineParameter defines model for ModelEngineParameter.
type ModelEngineParameter = DeploymentTargetEngine

// ModelTypeParameter defines model for ModelTypeParameter.
type ModelTypeParameter = KerasModelTypeEnum

// OptionalImpulseIdParameter defines model for OptionalImpulseIdParameter.
type OptionalImpulseIdParameter = int

// ProjectIdParameter defines model for ProjectIdParameter.
type ProjectIdParameter = int

// GetProjectInfoParams defines parameters for GetProjectInfo.
type GetProjectInfoParams struct {
	// ImpulseId Impulse ID. If this is unset then the default impulse is used.
	ImpulseId *OptionalImpulseIdParameter `form:"impulseId,omitempty" json:"impulseId,omitempty"`
}

// GetDeploymentParams defines parameters for GetDeployment.
type GetDeploymentParams struct {
	// Type The name of the built target. You can find this by listing all deployment targets through `listDeploymentTargetsForProject` (via `GET /v1/api/{projectId}/deployment/targets`) and see the `format` type.
	Type DeploymentTypeParameter `form:"type" json:"type"`

	// ModelType Optional model type of the build (if not, it uses the settings in the Keras block)
	ModelType *ModelTypeParameter `form:"modelType,omitempty" json:"modelType,omitempty"`

	// Engine Optional engine for the build (if not, it uses the default engine for the deployment target)
	Engine *ModelEngineParameter `form:"engine,omitempty" json:"engine,omitempty"`

	// ImpulseId Impulse ID. If this is unset then the default impulse is used.
	ImpulseId *OptionalImpulseIdParameter `form:"impulseId,omitempty" json:"impulseId,omitempty"`
}

// DownloadBuildParams defines parameters for DownloadBuild.
type DownloadBuildParams struct {
	// Type The name of the built target. You can find this by listing all deployment targets through `listDeploymentTargetsForProject` (via `GET /v1/api/{projectId}/deployment/targets`) and see the `format` type.
	Type DeploymentTypeParameter `form:"type" json:"type"`

	// ModelType Optional model type of the build (if not, it uses the settings in the Keras block)
	ModelType *ModelTypeParameter `form:"modelType,omitempty" json:"modelType,omitempty"`

	// Engine Optional engine for the build (if not, it uses the default engine for the deployment target)
	Engine *ModelEngineParameter `form:"engine,omitempty" json:"engine,omitempty"`

	// ImpulseId Impulse ID. If this is unset then the default impulse is used.
	ImpulseId *OptionalImpulseIdParameter `form:"impulseId,omitempty" json:"impulseId,omitempty"`
}

// BuildOnDeviceModelJobParams defines parameters for BuildOnDeviceModelJob.
type BuildOnDeviceModelJobParams struct {
	// Type The name of the built target. You can find this by listing all deployment targets through `listDeploymentTargetsForProject` (via `GET /v1/api/{projectId}/deployment/targets`) and see the `format` type.
	Type DeploymentTypeParameter `form:"type" json:"type"`

	// ImpulseId Impulse ID. If this is unset then the default impulse is used.
	ImpulseId *OptionalImpulseIdParameter `form:"impulseId,omitempty" json:"impulseId,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = GetJWTRequest

// UpdateProjectJSONRequestBody defines body for UpdateProject for application/json ContentType.
type UpdateProjectJSONRequestBody = UpdateProjectRequest

// BuildOnDeviceModelJobJSONRequestBody defines body for BuildOnDeviceModelJob for application/json ContentType.
type BuildOnDeviceModelJobJSONRequestBody = BuildOnDeviceModelRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// LoginWithBody request with any body
	LoginWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	Login(ctx context.Context, body LoginJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteProject request
	DeleteProject(ctx context.Context, projectId ProjectIdParameter, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetProjectInfo request
	GetProjectInfo(ctx context.Context, projectId ProjectIdParameter, params *GetProjectInfoParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateProjectWithBody request with any body
	UpdateProjectWithBody(ctx context.Context, projectId ProjectIdParameter, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateProject(ctx context.Context, projectId ProjectIdParameter, body UpdateProjectJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDeployment request
	GetDeployment(ctx context.Context, projectId ProjectIdParameter, params *GetDeploymentParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DownloadBuild request
	DownloadBuild(ctx context.Context, projectId ProjectIdParameter, params *DownloadBuildParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// BuildOnDeviceModelJobWithBody request with any body
	BuildOnDeviceModelJobWithBody(ctx context.Context, projectId ProjectIdParameter, params *BuildOnDeviceModelJobParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	BuildOnDeviceModelJob(ctx context.Context, projectId ProjectIdParameter, params *BuildOnDeviceModelJobParams, body BuildOnDeviceModelJobJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetJobStatus request
	GetJobStatus(ctx context.Context, projectId ProjectIdParameter, jobId JobIdParameter, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) LoginWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLoginRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Login(ctx context.Context, body LoginJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLoginRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteProject(ctx context.Context, projectId ProjectIdParameter, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteProjectRequest(c.Server, projectId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetProjectInfo(ctx context.Context, projectId ProjectIdParameter, params *GetProjectInfoParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetProjectInfoRequest(c.Server, projectId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateProjectWithBody(ctx context.Context, projectId ProjectIdParameter, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateProjectRequestWithBody(c.Server, projectId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateProject(ctx context.Context, projectId ProjectIdParameter, body UpdateProjectJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateProjectRequest(c.Server, projectId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetDeployment(ctx context.Context, projectId ProjectIdParameter, params *GetDeploymentParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDeploymentRequest(c.Server, projectId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DownloadBuild(ctx context.Context, projectId ProjectIdParameter, params *DownloadBuildParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDownloadBuildRequest(c.Server, projectId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BuildOnDeviceModelJobWithBody(ctx context.Context, projectId ProjectIdParameter, params *BuildOnDeviceModelJobParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBuildOnDeviceModelJobRequestWithBody(c.Server, projectId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BuildOnDeviceModelJob(ctx context.Context, projectId ProjectIdParameter, params *BuildOnDeviceModelJobParams, body BuildOnDeviceModelJobJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBuildOnDeviceModelJobRequest(c.Server, projectId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetJobStatus(ctx context.Context, projectId ProjectIdParameter, jobId JobIdParameter, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetJobStatusRequest(c.Server, projectId, jobId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewLoginRequest calls the generic Login builder with application/json body
func NewLoginRequest(server string, body LoginJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewLoginRequestWithBody(server, "application/json", bodyReader)
}

// NewLoginRequestWithBody generates requests for Login with any type of body
func NewLoginRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api-login")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteProjectRequest generates requests for DeleteProject
func NewDeleteProjectRequest(server string, projectId ProjectIdParameter) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "projectId", runtime.ParamLocationPath, projectId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetProjectInfoRequest generates requests for GetProjectInfo
func NewGetProjectInfoRequest(server string, projectId ProjectIdParameter, params *GetProjectInfoParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "projectId", runtime.ParamLocationPath, projectId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.ImpulseId != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "impulseId", runtime.ParamLocationQuery, *params.ImpulseId); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateProjectRequest calls the generic UpdateProject builder with application/json body
func NewUpdateProjectRequest(server string, projectId ProjectIdParameter, body UpdateProjectJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateProjectRequestWithBody(server, projectId, "application/json", bodyReader)
}

// NewUpdateProjectRequestWithBody generates requests for UpdateProject with any type of body
func NewUpdateProjectRequestWithBody(server string, projectId ProjectIdParameter, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "projectId", runtime.ParamLocationPath, projectId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetDeploymentRequest generates requests for GetDeployment
func NewGetDeploymentRequest(server string, projectId ProjectIdParameter, params *GetDeploymentParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "projectId", runtime.ParamLocationPath, projectId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/%s/deployment", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "type", runtime.ParamLocationQuery, params.Type); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.ModelType != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "modelType", runtime.ParamLocationQuery, *params.ModelType); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Engine != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "engine", runtime.ParamLocationQuery, *params.Engine); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.ImpulseId != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "impulseId", runtime.ParamLocationQuery, *params.ImpulseId); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDownloadBuildRequest generates requests for DownloadBuild
func NewDownloadBuildRequest(server string, projectId ProjectIdParameter, params *DownloadBuildParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "projectId", runtime.ParamLocationPath, projectId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/%s/deployment/download", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "type", runtime.ParamLocationQuery, params.Type); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.ModelType != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "modelType", runtime.ParamLocationQuery, *params.ModelType); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Engine != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "engine", runtime.ParamLocationQuery, *params.Engine); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.ImpulseId != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "impulseId", runtime.ParamLocationQuery, *params.ImpulseId); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewBuildOnDeviceModelJobRequest calls the generic BuildOnDeviceModelJob builder with application/json body
func NewBuildOnDeviceModelJobRequest(server string, projectId ProjectIdParameter, params *BuildOnDeviceModelJobParams, body BuildOnDeviceModelJobJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewBuildOnDeviceModelJobRequestWithBody(server, projectId, params, "application/json", bodyReader)
}

// NewBuildOnDeviceModelJobRequestWithBody generates requests for BuildOnDeviceModelJob with any type of body
func NewBuildOnDeviceModelJobRequestWithBody(server string, projectId ProjectIdParameter, params *BuildOnDeviceModelJobParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "projectId", runtime.ParamLocationPath, projectId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/%s/jobs/build-ondevice-model", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "type", runtime.ParamLocationQuery, params.Type); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.ImpulseId != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "impulseId", runtime.ParamLocationQuery, *params.ImpulseId); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetJobStatusRequest generates requests for GetJobStatus
func NewGetJobStatusRequest(server string, projectId ProjectIdParameter, jobId JobIdParameter) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "projectId", runtime.ParamLocationPath, projectId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "jobId", runtime.ParamLocationPath, jobId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/%s/jobs/%s/status", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// LoginWithBodyWithResponse request with any body
	LoginWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*LoginHTTPResponse, error)

	LoginWithResponse(ctx context.Context, body LoginJSONRequestBody, reqEditors ...RequestEditorFn) (*LoginHTTPResponse, error)

	// DeleteProjectWithResponse request
	DeleteProjectWithResponse(ctx context.Context, projectId ProjectIdParameter, reqEditors ...RequestEditorFn) (*DeleteProjectHTTPResponse, error)

	// GetProjectInfoWithResponse request
	GetProjectInfoWithResponse(ctx context.Context, projectId ProjectIdParameter, params *GetProjectInfoParams, reqEditors ...RequestEditorFn) (*GetProjectInfoHTTPResponse, error)

	// UpdateProjectWithBodyWithResponse request with any body
	UpdateProjectWithBodyWithResponse(ctx context.Context, projectId ProjectIdParameter, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateProjectHTTPResponse, error)

	UpdateProjectWithResponse(ctx context.Context, projectId ProjectIdParameter, body UpdateProjectJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateProjectHTTPResponse, error)

	// GetDeploymentWithResponse request
	GetDeploymentWithResponse(ctx context.Context, projectId ProjectIdParameter, params *GetDeploymentParams, reqEditors ...RequestEditorFn) (*GetDeploymentHTTPResponse, error)

	// DownloadBuildWithResponse request
	DownloadBuildWithResponse(ctx context.Context, projectId ProjectIdParameter, params *DownloadBuildParams, reqEditors ...RequestEditorFn) (*DownloadBuildHTTPResponse, error)

	// BuildOnDeviceModelJobWithBodyWithResponse request with any body
	BuildOnDeviceModelJobWithBodyWithResponse(ctx context.Context, projectId ProjectIdParameter, params *BuildOnDeviceModelJobParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*BuildOnDeviceModelJobHTTPResponse, error)

	BuildOnDeviceModelJobWithResponse(ctx context.Context, projectId ProjectIdParameter, params *BuildOnDeviceModelJobParams, body BuildOnDeviceModelJobJSONRequestBody, reqEditors ...RequestEditorFn) (*BuildOnDeviceModelJobHTTPResponse, error)

	// GetJobStatusWithResponse request
	GetJobStatusWithResponse(ctx context.Context, projectId ProjectIdParameter, jobId JobIdParameter, reqEditors ...RequestEditorFn) (*GetJobStatusHTTPResponse, error)
}

type LoginHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetJWTResponse
}

// Status returns HTTPResponse.Status
func (r LoginHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r LoginHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteProjectHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GenericApiResponse
}

// Status returns HTTPResponse.Status
func (r DeleteProjectHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteProjectHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetProjectInfoHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ProjectInfoResponse
}

// Status returns HTTPResponse.Status
func (r GetProjectInfoHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetProjectInfoHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateProjectHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GenericApiResponse
}

// Status returns HTTPResponse.Status
func (r UpdateProjectHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateProjectHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetDeploymentHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetDeploymentResponse
}

// Status returns HTTPResponse.Status
func (r GetDeploymentHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDeploymentHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DownloadBuildHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DownloadBuildHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DownloadBuildHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type BuildOnDeviceModelJobHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *StartJobResponse
}

// Status returns HTTPResponse.Status
func (r BuildOnDeviceModelJobHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BuildOnDeviceModelJobHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetJobStatusHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetJobResponse
}

// Status returns HTTPResponse.Status
func (r GetJobStatusHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetJobStatusHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// LoginWithBodyWithResponse request with arbitrary body returning *LoginHTTPResponse
func (c *ClientWithResponses) LoginWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*LoginHTTPResponse, error) {
	rsp, err := c.LoginWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLoginHTTPResponse(rsp)
}

func (c *ClientWithResponses) LoginWithResponse(ctx context.Context, body LoginJSONRequestBody, reqEditors ...RequestEditorFn) (*LoginHTTPResponse, error) {
	rsp, err := c.Login(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLoginHTTPResponse(rsp)
}

// DeleteProjectWithResponse request returning *DeleteProjectHTTPResponse
func (c *ClientWithResponses) DeleteProjectWithResponse(ctx context.Context, projectId ProjectIdParameter, reqEditors ...RequestEditorFn) (*DeleteProjectHTTPResponse, error) {
	rsp, err := c.DeleteProject(ctx, projectId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteProjectHTTPResponse(rsp)
}

// GetProjectInfoWithResponse request returning *GetProjectInfoHTTPResponse
func (c *ClientWithResponses) GetProjectInfoWithResponse(ctx context.Context, projectId ProjectIdParameter, params *GetProjectInfoParams, reqEditors ...RequestEditorFn) (*GetProjectInfoHTTPResponse, error) {
	rsp, err := c.GetProjectInfo(ctx, projectId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetProjectInfoHTTPResponse(rsp)
}

// UpdateProjectWithBodyWithResponse request with arbitrary body returning *UpdateProjectHTTPResponse
func (c *ClientWithResponses) UpdateProjectWithBodyWithResponse(ctx context.Context, projectId ProjectIdParameter, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateProjectHTTPResponse, error) {
	rsp, err := c.UpdateProjectWithBody(ctx, projectId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateProjectHTTPResponse(rsp)
}

func (c *ClientWithResponses) UpdateProjectWithResponse(ctx context.Context, projectId ProjectIdParameter, body UpdateProjectJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateProjectHTTPResponse, error) {
	rsp, err := c.UpdateProject(ctx, projectId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateProjectHTTPResponse(rsp)
}

// GetDeploymentWithResponse request returning *GetDeploymentHTTPResponse
func (c *ClientWithResponses) GetDeploymentWithResponse(ctx context.Context, projectId ProjectIdParameter, params *GetDeploymentParams, reqEditors ...RequestEditorFn) (*GetDeploymentHTTPResponse, error) {
	rsp, err := c.GetDeployment(ctx, projectId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDeploymentHTTPResponse(rsp)
}

// DownloadBuildWithResponse request returning *DownloadBuildHTTPResponse
func (c *ClientWithResponses) DownloadBuildWithResponse(ctx context.Context, projectId ProjectIdParameter, params *DownloadBuildParams, reqEditors ...RequestEditorFn) (*DownloadBuildHTTPResponse, error) {
	rsp, err := c.DownloadBuild(ctx, projectId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDownloadBuildHTTPResponse(rsp)
}

// BuildOnDeviceModelJobWithBodyWithResponse request with arbitrary body returning *BuildOnDeviceModelJobHTTPResponse
func (c *ClientWithResponses) BuildOnDeviceModelJobWithBodyWithResponse(ctx context.Context, projectId ProjectIdParameter, params *BuildOnDeviceModelJobParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*BuildOnDeviceModelJobHTTPResponse, error) {
	rsp, err := c.BuildOnDeviceModelJobWithBody(ctx, projectId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBuildOnDeviceModelJobHTTPResponse(rsp)
}

func (c *ClientWithResponses) BuildOnDeviceModelJobWithResponse(ctx context.Context, projectId ProjectIdParameter, params *BuildOnDeviceModelJobParams, body BuildOnDeviceModelJobJSONRequestBody, reqEditors ...RequestEditorFn) (*BuildOnDeviceModelJobHTTPResponse, error) {
	rsp, err := c.BuildOnDeviceModelJob(ctx, projectId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBuildOnDeviceModelJobHTTPResponse(rsp)
}

// GetJobStatusWithResponse request returning *GetJobStatusHTTPResponse
func (c *ClientWithResponses) GetJobStatusWithResponse(ctx context.Context, projectId ProjectIdParameter, jobId JobIdParameter, reqEditors ...RequestEditorFn) (*GetJobStatusHTTPResponse, error) {
	rsp, err := c.GetJobStatus(ctx, projectId, jobId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetJobStatusHTTPResponse(rsp)
}

// ParseLoginHTTPResponse parses an HTTP response from a LoginWithResponse call
func ParseLoginHTTPResponse(rsp *http.Response) (*LoginHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &LoginHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetJWTResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseDeleteProjectHTTPResponse parses an HTTP response from a DeleteProjectWithResponse call
func ParseDeleteProjectHTTPResponse(rsp *http.Response) (*DeleteProjectHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteProjectHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GenericApiResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetProjectInfoHTTPResponse parses an HTTP response from a GetProjectInfoWithResponse call
func ParseGetProjectInfoHTTPResponse(rsp *http.Response) (*GetProjectInfoHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetProjectInfoHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ProjectInfoResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseUpdateProjectHTTPResponse parses an HTTP response from a UpdateProjectWithResponse call
func ParseUpdateProjectHTTPResponse(rsp *http.Response) (*UpdateProjectHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateProjectHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GenericApiResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetDeploymentHTTPResponse parses an HTTP response from a GetDeploymentWithResponse call
func ParseGetDeploymentHTTPResponse(rsp *http.Response) (*GetDeploymentHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDeploymentHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetDeploymentResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseDownloadBuildHTTPResponse parses an HTTP response from a DownloadBuildWithResponse call
func ParseDownloadBuildHTTPResponse(rsp *http.Response) (*DownloadBuildHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DownloadBuildHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseBuildOnDeviceModelJobHTTPResponse parses an HTTP response from a BuildOnDeviceModelJobWithResponse call
func ParseBuildOnDeviceModelJobHTTPResponse(rsp *http.Response) (*BuildOnDeviceModelJobHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BuildOnDeviceModelJobHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest StartJobResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetJobStatusHTTPResponse parses an HTTP response from a GetJobStatusWithResponse call
func ParseGetJobStatusHTTPResponse(rsp *http.Response) (*GetJobStatusHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetJobStatusHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetJobResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
