version = 1

# Debian build scripts
[[annotations]]
path = "debian/**"
SPDX-FileCopyrightText = "Arduino s.r.l. and/or its affiliated companies"
SPDX-License-Identifier = "GPL-3.0-or-later"

# E2eTest
[[annotations]]
path = "internal/e2e/daemon/**"
SPDX-FileCopyrightText = "Arduino s.r.l. and/or its affiliated companies"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "**/testdata/**"
SPDX-FileCopyrightText = "Arduino s.r.l. and/or its affiliated companies"
SPDX-License-Identifier = "GPL-3.0-or-later"


# Tool-generated or configuration files.
[[annotations]]
path = [
  ".editorconfig",
  ".golangci.yml",
  ".gitignore",
  ".licensed.yml",
  ".licenses/**",
  "dprint.json",
  "adbd.Dockerfile",
  "Taskfile.yml",
  "go.mod",
  "go.sum",
]
SPDX-FileCopyrightText = "Arduino s.r.l. and/or its affiliated companies"
SPDX-License-Identifier = "GPL-3.0-or-later"
