#!/bin/sh

chown -R arduino:arduino /home/arduino/.arduino-app-cli/examples

systemctl enable arduino-orchestrator

if [ -d /run/systemd/system ]; then
  systemctl daemon-reload
  systemctl start arduino-orchestrator
fi
