// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Defines values for GetAppsParamsStatus.
const (
	Running GetAppsParamsStatus = "running"
	Stopped GetAppsParamsStatus = "stopped"
	Unknown GetAppsParamsStatus = "unknown"
)

// AppCloneRequest defines model for AppCloneRequest.
type AppCloneRequest struct {
	Icon *string `json:"icon,omitempty"`
	Name *string `json:"name,omitempty"`
}

// AppCloneResponse defines model for AppCloneResponse.
type AppCloneResponse struct {
	Id *string `json:"id,omitempty"`
}

// AppDetailBrick defines model for AppDetailBrick.
type AppDetailBrick struct {
	Icon      *string            `json:"icon,omitempty"`
	Id        string             `json:"id"`
	Name      string             `json:"name"`
	Variables *map[string]string `json:"variables,omitempty"`
}

// AppDetailResponse defines model for AppDetailResponse.
type AppDetailResponse struct {
	Bricks      *AppDetailBrick `json:"bricks,omitempty"`
	ByteSize    *int            `json:"byteSize,omitempty"`
	Default     *bool           `json:"default,omitempty"`
	Description *string         `json:"description,omitempty"`
	Example     *bool           `json:"example,omitempty"`
	Icon        *string         `json:"icon,omitempty"`
	Id          string          `json:"id"`
	Name        string          `json:"name"`
	Status      string          `json:"status"`
}

// AppListItem defines model for AppListItem.
type AppListItem struct {
	Default     *bool   `json:"default,omitempty"`
	Description *string `json:"description,omitempty"`
	Example     *bool   `json:"example,omitempty"`
	Icon        *string `json:"icon,omitempty"`
	Id          string  `json:"id"`
	Name        string  `json:"name"`
	Status      string  `json:"status"`
}

// AppListResponse defines model for AppListResponse.
type AppListResponse struct {
	Apps *[]AppListItem `json:"apps,omitempty"`
}

// AppPatchRequest defines model for AppPatchRequest.
type AppPatchRequest struct {
	Default   *bool                         `json:"default,omitempty"`
	Variables *map[string]map[string]string `json:"variables,omitempty"`
}

// Brick defines model for Brick.
type Brick struct {
	// Author The author of the brick.
	Author *string `json:"author,omitempty"`

	// Description A detailed description of the brick.
	Description *string `json:"description,omitempty"`

	// Icon An icon or emoji representing the brick.
	Icon *string `json:"icon,omitempty"`

	// Id The unique identifier of the brick.
	Id string `json:"id"`

	// IsInstalled Indicates whether the brick is installed.
	IsInstalled *bool `json:"is_installed,omitempty"`

	// Name The name of the brick.
	Name string `json:"name"`
}

// BrickDetails defines model for BrickDetails.
type BrickDetails struct {
	// Author The author of the brick.
	Author *string `json:"author,omitempty"`

	// Description A detailed description of the brick.
	Description *string `json:"description,omitempty"`

	// Icon An icon or emoji representing the brick.
	Icon *string `json:"icon,omitempty"`

	// Id The unique identifier of the brick.
	Id string `json:"id"`

	// IsInstalled Indicates whether the brick is installed.
	IsInstalled *bool `json:"is_installed,omitempty"`

	// Name The name of the brick.
	Name string `json:"name"`

	// Readme The readmefile
	Readme    *string                   `json:"readme,omitempty"`
	Variables *map[string]BrickVariable `json:"variables,omitempty"`
}

// BrickListResponse defines model for BrickListResponse.
type BrickListResponse struct {
	Pagination *Pagination `json:"pagination,omitempty"`
	Results    *[]Brick    `json:"results,omitempty"`
}

// BrickVariable defines model for BrickVariable.
type BrickVariable struct {
	// DefaultValue The default value
	DefaultValue *string `json:"default_value,omitempty"`

	// Description The variable description
	Description *string `json:"description,omitempty"`

	// Required If the variable is required
	Required *bool `json:"required,omitempty"`
}

// CreateAppRequest defines model for CreateAppRequest.
type CreateAppRequest struct {
	Bricks *[]string `json:"bricks,omitempty"`
	Icon   *string   `json:"icon,omitempty"`
	Name   *string   `json:"name,omitempty"`
}

// CreateAppResponse defines model for CreateAppResponse.
type CreateAppResponse struct {
	Id *string `json:"id,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    int     `json:"code"`
	Message *string `json:"message,omitempty"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	// NextPage The next page number (if available).
	NextPage *int `json:"next_page,omitempty"`

	// Page The current page number.
	Page int `json:"page"`

	// PerPage The number of items per page.
	PerPage int `json:"per_page"`

	// PrevPage The previous page number (if available).
	PrevPage *int `json:"prev_page,omitempty"`

	// TotalItems The total number of items.
	TotalItems int `json:"total_items"`

	// TotalPages The total number of pages.
	TotalPages int `json:"total_pages"`
}

// StreamedMessage defines model for StreamedMessage.
type StreamedMessage = string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// PreconditionFailed defines model for PreconditionFailed.
type PreconditionFailed = ErrorResponse

// GetAppsParams defines parameters for GetApps.
type GetAppsParams struct {
	Example *bool                  `form:"example,omitempty" json:"example,omitempty"`
	Default *bool                  `form:"default,omitempty" json:"default,omitempty"`
	Status  *[]GetAppsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// GetAppsParamsStatus defines parameters for GetApps.
type GetAppsParamsStatus string

// GetAppLogsParams defines parameters for GetAppLogs.
type GetAppLogsParams struct {
	Filter   *string `form:"filter,omitempty" json:"filter,omitempty"`
	Tail     *int    `form:"tail,omitempty" json:"tail,omitempty"`
	Nofollow *bool   `form:"nofollow,omitempty" json:"nofollow,omitempty"`
}

// GetMonitorParams defines parameters for GetMonitor.
type GetMonitorParams struct {
	Base64   *bool `form:"base64,omitempty" json:"base64,omitempty"`
	BaudRate *int  `form:"baud_rate,omitempty" json:"baud_rate,omitempty"`
}

// SendToMonitorJSONBody defines parameters for SendToMonitor.
type SendToMonitorJSONBody struct {
	Message *string `json:"message,omitempty"`
}

// SendToMonitorParams defines parameters for SendToMonitor.
type SendToMonitorParams struct {
	Base64 *bool `form:"base64,omitempty" json:"base64,omitempty"`
}

// CreateAppJSONRequestBody defines body for CreateApp for application/json ContentType.
type CreateAppJSONRequestBody = CreateAppRequest

// EditAppJSONRequestBody defines body for EditApp for application/json ContentType.
type EditAppJSONRequestBody = AppPatchRequest

// CloneAppJSONRequestBody defines body for CloneApp for application/json ContentType.
type CloneAppJSONRequestBody = AppCloneRequest

// SendToMonitorJSONRequestBody defines body for SendToMonitor for application/json ContentType.
type SendToMonitorJSONRequestBody SendToMonitorJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetApps request
	GetApps(ctx context.Context, params *GetAppsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateAppWithBody request with any body
	CreateAppWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateApp(ctx context.Context, body CreateAppJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteApp request
	DeleteApp(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAppDetails request
	GetAppDetails(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// EditAppWithBody request with any body
	EditAppWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	EditApp(ctx context.Context, id string, body EditAppJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CloneAppWithBody request with any body
	CloneAppWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CloneApp(ctx context.Context, id string, body CloneAppJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAppEvents request
	GetAppEvents(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAppLogs request
	GetAppLogs(ctx context.Context, id string, params *GetAppLogsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetMonitor request
	GetMonitor(ctx context.Context, id string, params *GetMonitorParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SendToMonitorWithBody request with any body
	SendToMonitorWithBody(ctx context.Context, id string, params *SendToMonitorParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SendToMonitor(ctx context.Context, id string, params *SendToMonitorParams, body SendToMonitorJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// StartApp request
	StartApp(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// StopApp request
	StopApp(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetBricks request
	GetBricks(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetBrickDetails request
	GetBrickDetails(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetApps(ctx context.Context, params *GetAppsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAppsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateAppWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateAppRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateApp(ctx context.Context, body CreateAppJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateAppRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteApp(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteAppRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAppDetails(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAppDetailsRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) EditAppWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewEditAppRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) EditApp(ctx context.Context, id string, body EditAppJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewEditAppRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CloneAppWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCloneAppRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CloneApp(ctx context.Context, id string, body CloneAppJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCloneAppRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAppEvents(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAppEventsRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAppLogs(ctx context.Context, id string, params *GetAppLogsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAppLogsRequest(c.Server, id, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetMonitor(ctx context.Context, id string, params *GetMonitorParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMonitorRequest(c.Server, id, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SendToMonitorWithBody(ctx context.Context, id string, params *SendToMonitorParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSendToMonitorRequestWithBody(c.Server, id, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SendToMonitor(ctx context.Context, id string, params *SendToMonitorParams, body SendToMonitorJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSendToMonitorRequest(c.Server, id, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) StartApp(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStartAppRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) StopApp(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStopAppRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetBricks(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetBricksRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetBrickDetails(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetBrickDetailsRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetAppsRequest generates requests for GetApps
func NewGetAppsRequest(server string, params *GetAppsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/apps")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Example != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "example", runtime.ParamLocationQuery, *params.Example); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Default != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "default", runtime.ParamLocationQuery, *params.Default); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Status != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "status", runtime.ParamLocationQuery, *params.Status); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateAppRequest calls the generic CreateApp builder with application/json body
func NewCreateAppRequest(server string, body CreateAppJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateAppRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateAppRequestWithBody generates requests for CreateApp with any type of body
func NewCreateAppRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/apps")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteAppRequest generates requests for DeleteApp
func NewDeleteAppRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/apps/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetAppDetailsRequest generates requests for GetAppDetails
func NewGetAppDetailsRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/apps/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewEditAppRequest calls the generic EditApp builder with application/json body
func NewEditAppRequest(server string, id string, body EditAppJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewEditAppRequestWithBody(server, id, "application/json", bodyReader)
}

// NewEditAppRequestWithBody generates requests for EditApp with any type of body
func NewEditAppRequestWithBody(server string, id string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/apps/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCloneAppRequest calls the generic CloneApp builder with application/json body
func NewCloneAppRequest(server string, id string, body CloneAppJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCloneAppRequestWithBody(server, id, "application/json", bodyReader)
}

// NewCloneAppRequestWithBody generates requests for CloneApp with any type of body
func NewCloneAppRequestWithBody(server string, id string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/apps/%s/clone", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetAppEventsRequest generates requests for GetAppEvents
func NewGetAppEventsRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/apps/%s/events", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetAppLogsRequest generates requests for GetAppLogs
func NewGetAppLogsRequest(server string, id string, params *GetAppLogsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/apps/%s/logs", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Filter != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "filter", runtime.ParamLocationQuery, *params.Filter); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Tail != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "tail", runtime.ParamLocationQuery, *params.Tail); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Nofollow != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "nofollow", runtime.ParamLocationQuery, *params.Nofollow); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetMonitorRequest generates requests for GetMonitor
func NewGetMonitorRequest(server string, id string, params *GetMonitorParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/apps/%s/monitor", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Base64 != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "base64", runtime.ParamLocationQuery, *params.Base64); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.BaudRate != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "baud_rate", runtime.ParamLocationQuery, *params.BaudRate); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSendToMonitorRequest calls the generic SendToMonitor builder with application/json body
func NewSendToMonitorRequest(server string, id string, params *SendToMonitorParams, body SendToMonitorJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSendToMonitorRequestWithBody(server, id, params, "application/json", bodyReader)
}

// NewSendToMonitorRequestWithBody generates requests for SendToMonitor with any type of body
func NewSendToMonitorRequestWithBody(server string, id string, params *SendToMonitorParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/apps/%s/monitor", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Base64 != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "base64", runtime.ParamLocationQuery, *params.Base64); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewStartAppRequest generates requests for StartApp
func NewStartAppRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/apps/%s/start", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewStopAppRequest generates requests for StopApp
func NewStopAppRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/apps/%s/stop", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetBricksRequest generates requests for GetBricks
func NewGetBricksRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/bricks")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetBrickDetailsRequest generates requests for GetBrickDetails
func NewGetBrickDetailsRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/bricks/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetAppsWithResponse request
	GetAppsWithResponse(ctx context.Context, params *GetAppsParams, reqEditors ...RequestEditorFn) (*GetAppsResp, error)

	// CreateAppWithBodyWithResponse request with any body
	CreateAppWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateAppResp, error)

	CreateAppWithResponse(ctx context.Context, body CreateAppJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateAppResp, error)

	// DeleteAppWithResponse request
	DeleteAppWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*DeleteAppResp, error)

	// GetAppDetailsWithResponse request
	GetAppDetailsWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetAppDetailsResp, error)

	// EditAppWithBodyWithResponse request with any body
	EditAppWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*EditAppResp, error)

	EditAppWithResponse(ctx context.Context, id string, body EditAppJSONRequestBody, reqEditors ...RequestEditorFn) (*EditAppResp, error)

	// CloneAppWithBodyWithResponse request with any body
	CloneAppWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CloneAppResp, error)

	CloneAppWithResponse(ctx context.Context, id string, body CloneAppJSONRequestBody, reqEditors ...RequestEditorFn) (*CloneAppResp, error)

	// GetAppEventsWithResponse request
	GetAppEventsWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetAppEventsResp, error)

	// GetAppLogsWithResponse request
	GetAppLogsWithResponse(ctx context.Context, id string, params *GetAppLogsParams, reqEditors ...RequestEditorFn) (*GetAppLogsResp, error)

	// GetMonitorWithResponse request
	GetMonitorWithResponse(ctx context.Context, id string, params *GetMonitorParams, reqEditors ...RequestEditorFn) (*GetMonitorResp, error)

	// SendToMonitorWithBodyWithResponse request with any body
	SendToMonitorWithBodyWithResponse(ctx context.Context, id string, params *SendToMonitorParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SendToMonitorResp, error)

	SendToMonitorWithResponse(ctx context.Context, id string, params *SendToMonitorParams, body SendToMonitorJSONRequestBody, reqEditors ...RequestEditorFn) (*SendToMonitorResp, error)

	// StartAppWithResponse request
	StartAppWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*StartAppResp, error)

	// StopAppWithResponse request
	StopAppWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*StopAppResp, error)

	// GetBricksWithResponse request
	GetBricksWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetBricksResp, error)

	// GetBrickDetailsWithResponse request
	GetBrickDetailsWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetBrickDetailsResp, error)
}

type GetAppsResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AppListResponse
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r GetAppsResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAppsResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateAppResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *CreateAppResponse
	JSON400      *BadRequest
	JSON409      *Conflict
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r CreateAppResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateAppResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteAppResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AppDetailResponse
	JSON400      *BadRequest
	JSON412      *PreconditionFailed
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r DeleteAppResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteAppResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetAppDetailsResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AppDetailResponse
	JSON412      *PreconditionFailed
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r GetAppDetailsResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAppDetailsResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type EditAppResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *BadRequest
	JSON412      *PreconditionFailed
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r EditAppResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r EditAppResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CloneAppResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *AppCloneResponse
	JSON400      *BadRequest
	JSON404      *NotFound
	JSON409      *Conflict
	JSON412      *PreconditionFailed
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r CloneAppResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CloneAppResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetAppEventsResp struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetAppEventsResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAppEventsResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetAppLogsResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *BadRequest
	JSON412      *PreconditionFailed
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r GetAppLogsResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAppLogsResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetMonitorResp struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetMonitorResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetMonitorResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type SendToMonitorResp struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r SendToMonitorResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SendToMonitorResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type StartAppResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON412      *PreconditionFailed
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r StartAppResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r StartAppResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type StopAppResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON412      *PreconditionFailed
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r StopAppResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r StopAppResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetBricksResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *BrickListResponse
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r GetBricksResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetBricksResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetBrickDetailsResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *BrickDetails
	JSON400      *BadRequest
	JSON404      *NotFound
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r GetBrickDetailsResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetBrickDetailsResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetAppsWithResponse request returning *GetAppsResp
func (c *ClientWithResponses) GetAppsWithResponse(ctx context.Context, params *GetAppsParams, reqEditors ...RequestEditorFn) (*GetAppsResp, error) {
	rsp, err := c.GetApps(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAppsResp(rsp)
}

// CreateAppWithBodyWithResponse request with arbitrary body returning *CreateAppResp
func (c *ClientWithResponses) CreateAppWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateAppResp, error) {
	rsp, err := c.CreateAppWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateAppResp(rsp)
}

func (c *ClientWithResponses) CreateAppWithResponse(ctx context.Context, body CreateAppJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateAppResp, error) {
	rsp, err := c.CreateApp(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateAppResp(rsp)
}

// DeleteAppWithResponse request returning *DeleteAppResp
func (c *ClientWithResponses) DeleteAppWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*DeleteAppResp, error) {
	rsp, err := c.DeleteApp(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteAppResp(rsp)
}

// GetAppDetailsWithResponse request returning *GetAppDetailsResp
func (c *ClientWithResponses) GetAppDetailsWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetAppDetailsResp, error) {
	rsp, err := c.GetAppDetails(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAppDetailsResp(rsp)
}

// EditAppWithBodyWithResponse request with arbitrary body returning *EditAppResp
func (c *ClientWithResponses) EditAppWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*EditAppResp, error) {
	rsp, err := c.EditAppWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseEditAppResp(rsp)
}

func (c *ClientWithResponses) EditAppWithResponse(ctx context.Context, id string, body EditAppJSONRequestBody, reqEditors ...RequestEditorFn) (*EditAppResp, error) {
	rsp, err := c.EditApp(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseEditAppResp(rsp)
}

// CloneAppWithBodyWithResponse request with arbitrary body returning *CloneAppResp
func (c *ClientWithResponses) CloneAppWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CloneAppResp, error) {
	rsp, err := c.CloneAppWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCloneAppResp(rsp)
}

func (c *ClientWithResponses) CloneAppWithResponse(ctx context.Context, id string, body CloneAppJSONRequestBody, reqEditors ...RequestEditorFn) (*CloneAppResp, error) {
	rsp, err := c.CloneApp(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCloneAppResp(rsp)
}

// GetAppEventsWithResponse request returning *GetAppEventsResp
func (c *ClientWithResponses) GetAppEventsWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetAppEventsResp, error) {
	rsp, err := c.GetAppEvents(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAppEventsResp(rsp)
}

// GetAppLogsWithResponse request returning *GetAppLogsResp
func (c *ClientWithResponses) GetAppLogsWithResponse(ctx context.Context, id string, params *GetAppLogsParams, reqEditors ...RequestEditorFn) (*GetAppLogsResp, error) {
	rsp, err := c.GetAppLogs(ctx, id, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAppLogsResp(rsp)
}

// GetMonitorWithResponse request returning *GetMonitorResp
func (c *ClientWithResponses) GetMonitorWithResponse(ctx context.Context, id string, params *GetMonitorParams, reqEditors ...RequestEditorFn) (*GetMonitorResp, error) {
	rsp, err := c.GetMonitor(ctx, id, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetMonitorResp(rsp)
}

// SendToMonitorWithBodyWithResponse request with arbitrary body returning *SendToMonitorResp
func (c *ClientWithResponses) SendToMonitorWithBodyWithResponse(ctx context.Context, id string, params *SendToMonitorParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SendToMonitorResp, error) {
	rsp, err := c.SendToMonitorWithBody(ctx, id, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSendToMonitorResp(rsp)
}

func (c *ClientWithResponses) SendToMonitorWithResponse(ctx context.Context, id string, params *SendToMonitorParams, body SendToMonitorJSONRequestBody, reqEditors ...RequestEditorFn) (*SendToMonitorResp, error) {
	rsp, err := c.SendToMonitor(ctx, id, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSendToMonitorResp(rsp)
}

// StartAppWithResponse request returning *StartAppResp
func (c *ClientWithResponses) StartAppWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*StartAppResp, error) {
	rsp, err := c.StartApp(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStartAppResp(rsp)
}

// StopAppWithResponse request returning *StopAppResp
func (c *ClientWithResponses) StopAppWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*StopAppResp, error) {
	rsp, err := c.StopApp(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStopAppResp(rsp)
}

// GetBricksWithResponse request returning *GetBricksResp
func (c *ClientWithResponses) GetBricksWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetBricksResp, error) {
	rsp, err := c.GetBricks(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetBricksResp(rsp)
}

// GetBrickDetailsWithResponse request returning *GetBrickDetailsResp
func (c *ClientWithResponses) GetBrickDetailsWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetBrickDetailsResp, error) {
	rsp, err := c.GetBrickDetails(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetBrickDetailsResp(rsp)
}

// ParseGetAppsResp parses an HTTP response from a GetAppsWithResponse call
func ParseGetAppsResp(rsp *http.Response) (*GetAppsResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAppsResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AppListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCreateAppResp parses an HTTP response from a CreateAppWithResponse call
func ParseCreateAppResp(rsp *http.Response) (*CreateAppResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateAppResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest CreateAppResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeleteAppResp parses an HTTP response from a DeleteAppWithResponse call
func ParseDeleteAppResp(rsp *http.Response) (*DeleteAppResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteAppResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AppDetailResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 412:
		var dest PreconditionFailed
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON412 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetAppDetailsResp parses an HTTP response from a GetAppDetailsWithResponse call
func ParseGetAppDetailsResp(rsp *http.Response) (*GetAppDetailsResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAppDetailsResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AppDetailResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 412:
		var dest PreconditionFailed
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON412 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseEditAppResp parses an HTTP response from a EditAppWithResponse call
func ParseEditAppResp(rsp *http.Response) (*EditAppResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &EditAppResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 412:
		var dest PreconditionFailed
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON412 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCloneAppResp parses an HTTP response from a CloneAppWithResponse call
func ParseCloneAppResp(rsp *http.Response) (*CloneAppResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CloneAppResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest AppCloneResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 412:
		var dest PreconditionFailed
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON412 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetAppEventsResp parses an HTTP response from a GetAppEventsWithResponse call
func ParseGetAppEventsResp(rsp *http.Response) (*GetAppEventsResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAppEventsResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetAppLogsResp parses an HTTP response from a GetAppLogsWithResponse call
func ParseGetAppLogsResp(rsp *http.Response) (*GetAppLogsResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAppLogsResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 412:
		var dest PreconditionFailed
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON412 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetMonitorResp parses an HTTP response from a GetMonitorWithResponse call
func ParseGetMonitorResp(rsp *http.Response) (*GetMonitorResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetMonitorResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseSendToMonitorResp parses an HTTP response from a SendToMonitorWithResponse call
func ParseSendToMonitorResp(rsp *http.Response) (*SendToMonitorResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SendToMonitorResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseStartAppResp parses an HTTP response from a StartAppWithResponse call
func ParseStartAppResp(rsp *http.Response) (*StartAppResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &StartAppResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 412:
		var dest PreconditionFailed
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON412 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseStopAppResp parses an HTTP response from a StopAppWithResponse call
func ParseStopAppResp(rsp *http.Response) (*StopAppResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &StopAppResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 412:
		var dest PreconditionFailed
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON412 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetBricksResp parses an HTTP response from a GetBricksWithResponse call
func ParseGetBricksResp(rsp *http.Response) (*GetBricksResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetBricksResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BrickListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetBrickDetailsResp parses an HTTP response from a GetBrickDetailsWithResponse call
func ParseGetBrickDetailsResp(rsp *http.Response) (*GetBrickDetailsResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetBrickDetailsResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BrickDetails
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
