// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAndApplyUpdate() {
  return window['go']['main']['App']['CheckAndApplyUpdate']();
}

export function GetLatestVersion() {
  return window['go']['main']['App']['GetLatestVersion']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}
