// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckAndApplyUpdate():Promise<void>;

export function Copy(arg1:string,arg2:string):Promise<void>;

export function GetLatestVersion():Promise<string>;

export function GetVersion():Promise<string>;

export function ListFiles(arg1:string):Promise<Array<main.FileInfo>>;

export function MkDirAll(arg1:string):Promise<void>;

export function MkTempDir(arg1:string):Promise<string>;

export function PullSync(arg1:string,arg2:string):Promise<void>;

export function PushSync(arg1:string,arg2:string):Promise<void>;

export function ReadFile(arg1:string):Promise<Array<number>>;

export function Remove(arg1:string):Promise<void>;

export function Rename(arg1:string,arg2:string):Promise<void>;

export function WriteFile(arg1:string,arg2:Array<number>):Promise<void>;
