// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAndApplyUpdate() {
  return window['go']['main']['App']['CheckAndApplyUpdate']();
}

export function Copy(arg1, arg2) {
  return window['go']['main']['App']['Copy'](arg1, arg2);
}

export function GetLatestVersion() {
  return window['go']['main']['App']['GetLatestVersion']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ListFiles(arg1) {
  return window['go']['main']['App']['ListFiles'](arg1);
}

export function MkDirAll(arg1) {
  return window['go']['main']['App']['MkDirAll'](arg1);
}

export function MkTempDir(arg1) {
  return window['go']['main']['App']['MkTempDir'](arg1);
}

export function PullSync(arg1, arg2) {
  return window['go']['main']['App']['PullSync'](arg1, arg2);
}

export function PushSync(arg1, arg2) {
  return window['go']['main']['App']['PushSync'](arg1, arg2);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function Remove(arg1) {
  return window['go']['main']['App']['Remove'](arg1);
}

export function Rename(arg1, arg2) {
  return window['go']['main']['App']['Rename'](arg1, arg2);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
