#!/bin/bash

USER_ID=1000

systemctl enable arduino-app-cli
systemctl enable arduino-avahi-serial.service

mkdir -p /etc/bash_completion.d/
export ARDUINO_APP_CLI__ALLOW_ROOT=true && arduino-app-cli completion bash > /etc/bash_completion.d/arduino-app-cli.bash || true

USER_NAME="$(getent passwd "$USER_ID" | cut -d: -f1)"
USER_HOME="$(getent passwd "$USER_ID" | cut -d: -f6)"

chown -R "$USER_NAME":arduino /var/lib/arduino-app-cli \
|| chown -R :arduino /var/lib/arduino-app-cli

chmod -R 775 /var/lib/arduino-app-cli

if [ "$1" = "configure" ] && [ -n "$USER_HOME" ]; then
    rm -rf "$USER_HOME/.local/share/arduino-app-cli"
fi

#LOAD_HELPER
configure_agent_profiles
