#!/bin/sh

set -e

systemctl enable arduino-app-cli
systemctl enable arduino-burn-bootloader
systemctl enable arduino-avahi-serial.service

delete_obsolete_files() {
  OBSOLETE_DIR="/home/arduino/.local/share/arduino-app-cli/examples"
    for i in "${OBSOLETE_DIR}"/*; do
      rm -rf "${i}"/.cache;
    done
}

if [ "$1" = "configure" ]; then
  # if $2 is not empty, this is an upgrade
  if [ -n "$2" ]; then
    # check if this is an upgrade from an old version
    if dpkg --compare-versions "$2" lt "0.8.0"; then
        echo "Running pre-0.7.0 legacy cleanup/migration..."
        delete_obsolete_files
    fi
  fi
fi