#!/bin/sh

set -e

APP_USER="arduino"
APP_GROUP="arduino"
SYSUPGRADE_GROUP="sysupgrade"

if ! getent group "$APP_GROUP" >/dev/null 2>&1; then
    addgroup "$APP_GROUP"
fi

if ! getent passwd "$APP_USER" >/dev/null 2>&1; then
    adduser \
        --ingroup "$APP_GROUP" \
        --home "/home/$APP_USER" \
        --shell /bin/false \
        --disabled-password \
        "$APP_USER" >/dev/null
fi

if ! getent group "$SYSUPGRADE_GROUP" >/dev/null 2>&1; then
    groupadd --system "$SYSUPGRADE_GROUP"
fi
usermod -aG "$SYSUPGRADE_GROUP" "$APP_USER"

# SHARED_FUNCTIONS
if [ "$1" = "upgrade" ]; then
    cleanup_arduino_examples /home/arduino/.local/share/arduino-app-cli/examples
    mkdir -p /var/lib/arduino-app-cli
    copy_if_exists /home/arduino/.local/share/arduino-app-cli/examples /var/lib/arduino-app-cli
    copy_if_exists /home/arduino/.local/share/arduino-app-cli/properties.msgpack* /var/lib/arduino-app-cli
    copy_if_exists /home/arduino/.local/share/arduino-app-cli/bootloader_burned.flag /var/lib/arduino-app-cli
fi
