#!/bin/sh

systemctl disable arduino-app-cli
systemctl disable arduino-burn-bootloader
systemctl disable arduino-avahi-serial.service
systemctl disable pipewire-no-session.path
systemctl disable pipewire-no-session.service
