#!/bin/sh

set -e
systemctl disable arduino-app-cli
systemctl disable arduino-burn-bootloader
systemctl disable arduino-avahi-serial.service

# SHARED_FUNCTIONS

echo "Running pre-0.8.0 legacy cleanup/migration..."
cleanup_arduino_examples /home/arduino/.local/share/arduino-app-cli/examples
echo "Cache cleanup..."
cleanup_arduino_examples /var/lib/arduino-app-cli/examples